-- MySQL Script generated by MySQL Workbench
-- Sun Jan 24 17:44:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema readme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema readme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `readme` DEFAULT CHARACTER SET utf8mb4 ;
USE `readme` ;

-- -----------------------------------------------------
-- Table `readme`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`user` ;

CREATE TABLE IF NOT EXISTS `readme`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_registration` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `email` VARCHAR(128) NOT NULL,
  `username` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `avatar` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`content_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`content_type` ;

CREATE TABLE IF NOT EXISTS `readme`.`content_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(128) NOT NULL,
  `icon` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `content_type_idx` (`type` ASC) ,
  UNIQUE INDEX `content_icon_idx` (`icon` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`post` ;

CREATE TABLE IF NOT EXISTS `readme`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `header` VARCHAR(128) NOT NULL,
  `content_text` TEXT NULL DEFAULT NULL,
  `cite_author` VARCHAR(128) NULL DEFAULT NULL,
  `content_media` VARCHAR(128) NULL DEFAULT NULL,
  `views` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NOT NULL,
  `content_type_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `post_user_idx` (`user_id` ASC) ,
  INDEX `post_content_type_idx` (`content_type_id` ASC) ,
  CONSTRAINT `post_user_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `readme`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_content_type_idx`
    FOREIGN KEY (`content_type_id`)
    REFERENCES `readme`.`content_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`comments` ;

CREATE TABLE IF NOT EXISTS `readme`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `content` TEXT NOT NULL,
  `user_id` INT(11) NOT NULL,
  `post_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `comment_user_idx` (`user_id` ASC) ,
  INDEX `comment_post_idx` (`post_id` ASC) ,
  CONSTRAINT `comment_user_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `readme`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comment_post_idx`
    FOREIGN KEY (`post_id`)
    REFERENCES `readme`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`hashtag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`hashtag` ;

CREATE TABLE IF NOT EXISTS `readme`.`hashtag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `hashtag_name_idx` (`name` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`likes` ;

CREATE TABLE IF NOT EXISTS `readme`.`likes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `post_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `like_user_idx` (`user_id` ASC) ,
  INDEX `like_post_idx` (`post_id` ASC) ,
  UNIQUE INDEX `user_post_idx` (`user_id` ASC, `post_id` ASC) ,
  CONSTRAINT `like_user_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `readme`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `like_post_idx`
    FOREIGN KEY (`post_id`)
    REFERENCES `readme`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`messages` ;

CREATE TABLE IF NOT EXISTS `readme`.`messages` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `content` TEXT NOT NULL,
  `sender_id` INT(11) NOT NULL,
  `receiver_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `message_sender_idx` (`sender_id` ASC) ,
  INDEX `message_receiver_idx_idx` (`receiver_id` ASC) ,
  CONSTRAINT `message_sender_idx`
    FOREIGN KEY (`sender_id`)
    REFERENCES `readme`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `message_receiver_idx`
    FOREIGN KEY (`receiver_id`)
    REFERENCES `readme`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`subscription` ;

CREATE TABLE IF NOT EXISTS `readme`.`subscription` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `subscriber_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `subscription_author_idx` (`subscriber_id` ASC) ,
  UNIQUE INDEX `subscription_subscriber_idx` (`user_id` ASC, `subscriber_id` ASC) ,
  CONSTRAINT `subscription_author_idx`
    FOREIGN KEY (`user_id`)
    REFERENCES `readme`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `subscription_subscriber_idx`
    FOREIGN KEY (`subscriber_id`)
    REFERENCES `readme`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `readme`.`hashtag_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `readme`.`hashtag_post` ;

CREATE TABLE IF NOT EXISTS `readme`.`hashtag_post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `post_id` INT(11) NOT NULL,
  `hashtag_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `post_has_hashtag_idx` (`post_id` ASC) ,
  INDEX `post_hashtag_idx` (`hashtag_id` ASC) ,
  CONSTRAINT `post_has_hashtag_idx`
    FOREIGN KEY (`post_id`)
    REFERENCES `readme`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `post_hashtag_idx`
    FOREIGN KEY (`hashtag_id`)
    REFERENCES `readme`.`hashtag` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
